on: [push]

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
      - name: Send GitHub trigger payload to Slack Workflow Builder
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          method: chat.postMessage
          payload: |
            "channel": "C0123456789",
            "text": "messages make meeting"
            "blocks": [
              { "type": "divider" },
              {
                "type": "image",
                "title": {
                  "type": "plain_text",
                  "text": "Slack Slack Slack",
                  "emoji": true
                },
                "image_url": "https://media.makeameme.org/created/a-slack-this.jpg",
                "alt_text": "marg"
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "${{ github.sha }}"
                    },
                    "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
