on: [push]

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
    - name: Send GitHub trigger payload to Slack Workflow Builder
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: 'SLACK_CHANNEL_ID' # ID of Slack Channel you want to post to
        payload: "{\"text\": \"posting from a github action\"}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
