# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Post blocks found in a file
on:
  push:
    branches:
      - main
jobs:
  run:
    name: Share a travel review to channel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Forward a saved message
        uses: slackapi/slack-github-action@v2.1.0
        with:
          payload-file-path: "./example-workflows/Technique_3_Slack_Incoming_Webhook/saved.data.json"
          payload-templated: true
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
        env:
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
