on: [push]

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
    - name: Send GitHub trigger payload to Slack Workflow Builder
      id: slack
      uses: slackapi/slack-github-action@v1.21.0
      with:
        payload: |
          {
            "key": "value",
            "foo": "bar"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
