# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Update a channel topic
on:
  push:
    branches:
      - main
jobs:
  run:
    name: Keep track of the main branch
    runs-on: ubuntu-latest
    steps:
      - name: Update the channel topic
        uses: slackapi/slack-github-action@v2.1.1
        with:
          payload-delimiter: "_"
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
