name: Sync tools docs to site repo

on:
  push:
    branches:
      - main
    paths:
      - "docs/**" 
  pull_request:
    branches:
      - main
    paths:
      - "docs/**" 
  workflow_dispatch:

jobs:

  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a GitHub token
        id: ghtoken
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          owner: slackapi
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

  call-sync-from-tools-docs-workflow:
    needs: get-token
    uses: slackapi/another-repo/.github/workflows/sync-from-tools-docs.yml@main
    secrets:
      token: ${{ needs.get-token.outputs.token }}
