name: Sync docs to docs site repo

on:
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
  push:
    branches:
      - main
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:

      - name: Generate a GitHub token
        id: ghtoken
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          owner: slackapi
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout private actions repo
        uses: actions/checkout@v4
        with:
          repository: slackapi/slackapi.github.io
          token: ${{ steps.ghtoken.outputs.token }}
          persist-credentials: false
          path: docs_repo

      - name: Run sync-docs action
        uses: ./docs_repo/.github/actions/sync-from-tools-docs