name: test

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - id: slack
      uses: ../action.yml
      with:
        channel-id: C0GHE0CV6
        payload: |
          {
            "text": "Deployment started (In Progress)",
            "attachments": [
              {
                "pretext": "Deployment started",
                "color": "dbab09",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "In Progress"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
    - uses: ../action.yml
      with:
        channel-id: C0GHE0CV6
        update-ts: ${{ steps.slack.outputs.ts }}
        payload: |
          {
            "text": "Deployment finished (Completed)",
            "attachments": [
              {
                "pretext": "Deployment finished",
                "color": "28a745",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "Completed"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}